# src/teleauto/localization.py

CURRENT_LANG = "ru"

LANG_CODES = {
    "💩 Russian": "ru",
    "🇺🇸 English": "en",
    "🇺🇦 Ukrainian": "ua"
}
LANG_NAMES = {v: k for k, v in LANG_CODES.items()}

TRANSLATIONS = {
    "ru": {
        # GUI
        "window_title_setup": "Первичная настройка",
        "window_title_pin": "Ввод PIN",
        "window_title_settings": "Настройки",
        "pin_label": "PIN-код:",
        "pin_repeat": "Повторите PIN:",
        "pin_enter_msg": "Введите ваш PIN-код:",
        "secret_1": "Секрет 2FA (Профиль 1):",
        "secret_2": "Секрет 2FA (Профиль 2):",
        "secret_3": "Секрет 2FA (Профиль 3):",
        "secret_hint": "Заполняйте по порядку профилей в Pritunl",
        "auto_start_tm": "Автозапуск Telemart",
        "login": "Логин:",
        "password": "Пароль:",
        "save_btn": "Сохранить и продолжить",
        "save_changes_btn": "Сохранить изменения",
        "unlock_btn": "Разблокировать",
        "delete_btn": "Сброс данных",
        "delete_confirm": "Вы уверены? Это удалит все данные.",
        "error_pin_mismatch": "PIN коды не совпадают.",
        "error_no_secret": "Укажите хотя бы один секрет 2FA.",
        "error_wrong_pin": "Неверный PIN.",
        "group_security": "БЕЗОПАСНОСТЬ",
        "group_vpn": "VPN ПРОФИЛИ (2FA)",
        "group_tm": "TELEMART AUTOMATION",
        "group_access": "ДОСТУП К НАСТРОЙКАМ",
        "status_waiting": "Ожидание",
        "status_off": "Отключен",
        "status_working": "Работа...",
        "status_success": "Успешно",
        "status_error": "Ошибка",
        "status_no_net": "Нет сети",
        "status_active": "Активен",
        "update_label": "Обновление",
        "update_actual": "Актуально",
        "btn_start": "Старт",
        "btn_disconnect": "Стоп",
        "lang_label": "Язык / Language:",
        "restart_title": "Требуется перезапуск",
        "restart_msg": "Язык интерфейса изменен.\nПожалуйста, перезапустите программу для применения настроек.",

        # LOGS (General)
        "log_system_start": "--- Запуск Системы ---",

        # LOGS (Network Utils)
        "log_net_checking": "Проверка подключения к интернету через {host}...",
        "log_net_available": "Интернет доступен.",
        "log_net_unavailable": "Интернет недоступен, пробуем снова...",
        "log_net_ping_err": "Ошибка пинга: {e}",

        # LOGS (TOTP / Time)
        "log_time_drift_warn": "Внимание! Системное время отличается от реального на {drift:.2f} сек.",
        "log_time_sync_rec": "Рекомендуется синхронизировать время на компьютере.",
        "log_time_ntp_err": "Ошибка проверки времени через NTP: {e}",

        # LOGS (VPN Connect)
        "log_vpn_check_pre": "Проверка окна Pritunl...",
        "log_vpn_window_found": "Окно Pritunl найдено, видимость: {visible}",
        "log_vpn_restart": "Окно невидимо. Перезапускаем...",
        "log_vpn_start": "Запуск Pritunl...",
        "log_vpn_ready": "Pritunl готов.",
        "log_vpn_connect_click": "Нажата кнопка Connect для профиля #{idx}",
        "log_vpn_totp": "Введен код TOTP.",
        "log_vpn_reconnect_click": "Нажата кнопка Connect (после 2FA).",
        "log_vpn_disconnect_click": "Нажата кнопка Disconnect.",
        "log_vpn_adapters_off": "Адаптеры отключены.",
        "log_vpn_attempt": "Попытка подключения...",
        "log_vpn_connected": "VPN Подключен!",
        "log_vpn_error": "Ошибка VPN: {e}",
        "log_vpn_visible_error": "Ошибка проверки видимости: {e}",
        "log_vpn_search_error": "Ошибка поиска окна: {e}",
        "log_vpn_kill_error": "Ошибка завершения процесса: {e}",
        "log_vpn_check_error": "Ошибка проверки Pritunl: {e}",
        "log_vpn_connect_click_error": "Ошибка нажатия Connect: {e}",

        # LOGS (Monitor)
        "log_mon_init": "VPN Monitor инициализирован для P#{idx}",
        "log_mon_vpn_check_err": "Ошибка проверки VPN: {e}",
        "log_mon_internet_check": "Проверяем интернет...",
        "log_mon_reconnect_profile": "Переподключение VPN (P#{idx})...",
        "log_mon_time_fix": "Исправьте системное время и нажмите Enter...",
        "log_mon_totp_fail": "Не удалось получить TOTP код",
        "log_mon_restore_start": "Восстановление соединения...",
        "log_mon_click_fail": "Не удалось нажать Connect для P{idx}",
        "log_mon_reconnect_err": "Ошибка переподключения: {e}",
        "log_mon_loop_start": "Запуск цикла мониторинга...",
        "log_mon_status": "VPN статус: {status}",
        "log_mon_vpn_down": "VPN отключен! Попытка переподключения...",
        "log_mon_reconnect_success": "Переподключение успешно",
        "log_mon_loop_err": "Ошибка мониторинга: {e}",
        "log_mon_no_secret": "Нет секрета 2FA (P{idx})",
        "log_mon_bg_start": "Мониторинг запущен в фоне",
        "log_mon_stop": "Остановка VPN Monitor...",
        "status_connected": "ПОДКЛЮЧЕН",
        "status_disconnected": "ОТКЛЮЧЕН",
        "state_connected_lower": "подключен",
        "state_disconnected_lower": "отключен",
        "log_mon_initial_state": "Начальное состояние VPN: {state}",

        # LOGS (Telemart)
        "log_tm_launching": "Запускаем Telemart Client...",
        "log_tm_launched": "Telemart Client запущен",
        "log_tm_already_running": "Telemart уже запущен",
        "log_tm_check_err": "Ошибка проверки Telemart: {e}",
        "log_tm_wait_login": "Ждем поле логина...",
        "log_tm_login_found": "Поле логина найдено",
        "log_tm_login_not_found": "Поле логина не найдено... ({attempt}/180)",
        "log_tm_window_not_found": "Окно не найдено... ({attempt}/180)",
        "log_tm_search_err": "Ошибка поиска поля логина: {e}",
        "log_tm_timeout": "Поле логина не появилось за 3 мин",
        "log_tm_performing_login": "Выполняем вход...",
        "log_tm_err_login_field": "Поле логина не найдено!",
        "log_tm_login_entered": "Логин введен",
        "log_tm_err_pass_field": "Поле пароля не найдено!",
        "log_tm_pass_entered": "Пароль введен",
        "log_tm_err_btn": "Кнопка Вход не найдена!",
        "log_tm_btn_clicked": "Кнопка Вход нажата",
        "log_tm_login_err": "Ошибка входа: {e}",
        "log_tm_update_cycle": "Цикл обновления {current}/{max}",
        "log_tm_login_ok": "Вход выполнен успешно",
        "log_tm_update_fail": "Не удалось войти после обновлений",
        "log_tm_start": "Запуск Telemart...",
        "log_tm_login": "Вход в аккаунт...",
        "log_tm_success": "Вход выполнен!",
        "log_monitor_start": "Запуск монитора...",
    },
    "en": {
        # GUI
        "window_title_setup": "Initial Setup",
        "window_title_pin": "Enter PIN",
        "window_title_settings": "Settings",
        "pin_label": "PIN Code:",
        "pin_repeat": "Repeat PIN:",
        "pin_enter_msg": "Enter your PIN code:",
        "secret_1": "2FA Secret (Profile 1):",
        "secret_2": "2FA Secret (Profile 2):",
        "secret_3": "2FA Secret (Profile 3):",
        "secret_hint": "Fill in order of Pritunl profiles",
        "auto_start_tm": "Auto-start Telemart",
        "login": "Login:",
        "password": "Password:",
        "save_btn": "Save & Continue",
        "save_changes_btn": "Save Changes",
        "unlock_btn": "Unlock",
        "delete_btn": "Reset Data",
        "delete_confirm": "Are you sure? This deletes all data.",
        "error_pin_mismatch": "PINs do not match.",
        "error_no_secret": "Provide at least one 2FA secret.",
        "error_wrong_pin": "Wrong PIN.",
        "group_security": "SECURITY",
        "group_vpn": "VPN PROFILES (2FA)",
        "group_tm": "TELEMART AUTOMATION",
        "group_access": "SETTINGS ACCESS",
        "status_waiting": "Waiting",
        "status_off": "Disconnected",
        "status_working": "Working...",
        "status_success": "Success",
        "status_error": "Error",
        "status_no_net": "No Net",
        "status_active": "Active",
        "update_label": "Update",
        "update_actual": "Up to date",
        "btn_start": "Start",
        "btn_disconnect": "Stop",
        "lang_label": "Language:",
        "restart_title": "Restart Required",
        "restart_msg": "Language changed.\nPlease restart the application to apply settings.",

        # LOGS
        "log_system_start": "--- System Start ---",
        "log_net_checking": "Checking internet via {host}...",
        "log_net_available": "Internet available.",
        "log_net_unavailable": "Internet unavailable, retrying...",
        "log_net_ping_err": "Ping error: {e}",

        "log_time_drift_warn": "Warning! System time drift: {drift:.2f} sec.",
        "log_time_sync_rec": "Please synchronize system time.",
        "log_time_ntp_err": "NTP check error: {e}",

        "log_vpn_check_pre": "Checking Pritunl window...",
        "log_vpn_window_found": "Pritunl found, visible: {visible}",
        "log_vpn_restart": "Window hidden. Restarting...",
        "log_vpn_start": "Starting Pritunl...",
        "log_vpn_ready": "Pritunl ready.",
        "log_vpn_connect_click": "Clicked Connect for profile #{idx}",
        "log_vpn_totp": "TOTP entered.",
        "log_vpn_reconnect_click": "Clicked Connect (after 2FA).",
        "log_vpn_disconnect_click": "Clicked Disconnect.",
        "log_vpn_adapters_off": "Adapters disconnected.",
        "log_vpn_attempt": "Connecting VPN...",
        "log_vpn_connected": "VPN Connected!",
        "log_vpn_error": "VPN Error: {e}",
        "log_vpn_visible_error": "Visibility check error: {e}",
        "log_vpn_search_error": "Search error: {e}",
        "log_vpn_kill_error": "Kill process error: {e}",
        "log_vpn_check_error": "Pritunl check error: {e}",
        "log_vpn_connect_click_error": "Connect click error: {e}",

        "log_mon_init": "VPN Monitor init for P#{idx}",
        "log_mon_vpn_check_err": "VPN check error: {e}",
        "log_mon_internet_check": "Checking internet...",
        "log_mon_reconnect_profile": "Reconnecting VPN (P#{idx})...",
        "log_mon_time_fix": "Fix system time and press Enter...",
        "log_mon_totp_fail": "Failed to get TOTP",
        "log_mon_restore_start": "Restoring connection...",
        "log_mon_click_fail": "Failed to click Connect for P{idx}",
        "log_mon_reconnect_err": "Reconnect error: {e}",
        "log_mon_loop_start": "Starting monitor loop...",
        "log_mon_status": "VPN Status: {status}",
        "log_mon_vpn_down": "VPN Down! Reconnecting...",
        "log_mon_reconnect_success": "Reconnect successful",
        "log_mon_loop_err": "Monitor error: {e}",
        "log_mon_no_secret": "No 2FA secret (P{idx})",
        "log_mon_bg_start": "Monitor running in background",
        "log_mon_stop": "Stopping VPN Monitor...",
        "status_connected": "CONNECTED",
        "status_disconnected": "DISCONNECTED",
        "state_connected_lower": "connected",
        "state_disconnected_lower": "disconnected",
        "log_mon_initial_state": "Initial VPN state: {state}",

        "log_tm_launching": "Launching Telemart Client...",
        "log_tm_launched": "Telemart Client launched",
        "log_tm_already_running": "Telemart already running",
        "log_tm_check_err": "Telemart check error: {e}",
        "log_tm_wait_login": "Waiting for login box...",
        "log_tm_login_found": "Login box found",
        "log_tm_login_not_found": "Login box not found... ({attempt}/180)",
        "log_tm_window_not_found": "Window not found... ({attempt}/180)",
        "log_tm_search_err": "Search error: {e}",
        "log_tm_timeout": "Login box timeout (3 min)",
        "log_tm_performing_login": "Performing login...",
        "log_tm_err_login_field": "Login field not found!",
        "log_tm_login_entered": "Login entered",
        "log_tm_err_pass_field": "Password field not found!",
        "log_tm_pass_entered": "Password entered",
        "log_tm_err_btn": "Enter button not found!",
        "log_tm_btn_clicked": "Enter clicked",
        "log_tm_login_err": "Login error: {e}",
        "log_tm_update_cycle": "Update cycle {current}/{max}",
        "log_tm_login_ok": "Login successful",
        "log_tm_update_fail": "Login failed after updates",

        "log_tm_start": "Starting Telemart...",
        "log_tm_login": "Logging in...",
        "log_tm_success": "Login Successful!",
        "log_monitor_start": "Starting Monitor...",
    },
    "ua": {
        # GUI
        "window_title_setup": "Початкове налаштування",
        "window_title_pin": "Введення PIN",
        "window_title_settings": "Налаштування",
        "pin_label": "PIN-код:",
        "pin_repeat": "Повторіть PIN:",
        "pin_enter_msg": "Введіть ваш PIN-код:",
        "secret_1": "Секрет 2FA (Профіль 1):",
        "secret_2": "Секрет 2FA (Профіль 2):",
        "secret_3": "Секрет 2FA (Профіль 3):",
        "secret_hint": "Заповнюйте по порядку профілів у Pritunl",
        "auto_start_tm": "Автозапуск Telemart",
        "login": "Логін:",
        "password": "Пароль:",
        "save_btn": "Зберегти та продовжити",
        "save_changes_btn": "Зберегти зміни",
        "unlock_btn": "Розблокувати",
        "delete_btn": "Скидання даних",
        "delete_confirm": "Ви впевнені? Це видалить усі дані.",
        "error_pin_mismatch": "PIN коди не співпадають.",
        "error_no_secret": "Вкажіть хоча б один секрет 2FA.",
        "error_wrong_pin": "Невірний PIN.",
        "group_security": "БЕЗПЕКА",
        "group_vpn": "VPN ПРОФІЛІ (2FA)",
        "group_tm": "TELEMART АВТОМАТИЗАЦІЯ",
        "group_access": "ДОСТУП ДО НАЛАШТУВАНЬ",
        "status_waiting": "Очікування",
        "status_off": "Вимкнено",
        "status_working": "Робота...",
        "status_success": "Успішно",
        "status_error": "Помилка",
        "status_no_net": "Немає мережі",
        "status_active": "Активний",
        "update_label": "Оновлення",
        "update_actual": "Актуально",
        "btn_start": "Старт",
        "btn_disconnect": "Стоп",
        "lang_label": "Мова / Language:",
        "restart_title": "Необхідний перезапуск",
        "restart_msg": "Мову змінено.\nБудь ласка, перезапустіть програму для застосування змін.",

        # LOGS
        "log_system_start": "--- Запуск Системи ---",

        "log_net_checking": "Перевірка інтернету через {host}...",
        "log_net_available": "Інтернет є.",
        "log_net_unavailable": "Інтернет недоступний, ще раз...",
        "log_net_ping_err": "Помилка пінгу: {e}",

        "log_time_drift_warn": "Увага! Відхилення часу: {drift:.2f} сек.",
        "log_time_sync_rec": "Рекомендується синхронізація часу.",
        "log_time_ntp_err": "Помилка NTP: {e}",

        "log_vpn_check_pre": "Перевірка вікна Pritunl...",
        "log_vpn_window_found": "Вікно Pritunl знайдено, видимість: {visible}",
        "log_vpn_restart": "Вікно невидиме. Перезапуск...",
        "log_vpn_start": "Запуск Pritunl...",
        "log_vpn_ready": "Pritunl готовий.",
        "log_vpn_connect_click": "Натиснуто Connect для профілю #{idx}",
        "log_vpn_totp": "Введено код TOTP.",
        "log_vpn_reconnect_click": "Натиснуто Connect (після 2FA).",
        "log_vpn_disconnect_click": "Натиснуто Disconnect.",
        "log_vpn_adapters_off": "Адаптери вимкнено.",
        "log_vpn_attempt": "Спроба підключення...",
        "log_vpn_connected": "VPN Підключено!",
        "log_vpn_error": "Помилка VPN: {e}",
        "log_vpn_visible_error": "Помилка видимості: {e}",
        "log_vpn_search_error": "Помилка пошуку вікна: {e}",
        "log_vpn_kill_error": "Помилка зупинки процесу: {e}",
        "log_vpn_check_error": "Помилка перевірки Pritunl: {e}",
        "log_vpn_connect_click_error": "Помилка кліку Connect: {e}",

        "log_mon_init": "VPN Monitor ініціалізовано для P#{idx}",
        "log_mon_vpn_check_err": "Помилка перевірки VPN: {e}",
        "log_mon_internet_check": "Перевірка інтернету...",
        "log_mon_reconnect_profile": "Перепідключення VPN (P#{idx})...",
        "log_mon_time_fix": "Виправте системний час і натисніть Enter...",
        "log_mon_totp_fail": "Не вдалося отримати TOTP",
        "log_mon_restore_start": "Відновлення з'єднання...",
        "log_mon_click_fail": "Не вдалося натиснути Connect для P{idx}",
        "log_mon_reconnect_err": "Помилка перепідключення: {e}",
        "log_mon_loop_start": "Запуск циклу моніторингу...",
        "log_mon_status": "Статус VPN: {status}",
        "log_mon_vpn_down": "VPN Вимкнено! Перепідключення...",
        "log_mon_reconnect_success": "Успішно перепідключено",
        "log_mon_loop_err": "Помилка монітора: {e}",
        "log_mon_no_secret": "Немає секрету 2FA (P{idx})",
        "log_mon_bg_start": "Монітор працює у фоні",
        "log_mon_stop": "Зупинка VPN Monitor...",
        "status_connected": "ПІДКЛЮЧЕНО",
        "status_disconnected": "ВІДКЛЮЧЕНО",
        "state_connected_lower": "підключено",
        "state_disconnected_lower": "відключено",
        "log_mon_initial_state": "Початковий стан VPN: {state}",

        "log_tm_launching": "Запускаємо Telemart Client...",
        "log_tm_launched": "Telemart Client запущено",
        "log_tm_already_running": "Telemart вже працює",
        "log_tm_check_err": "Помилка перевірки Telemart: {e}",
        "log_tm_wait_login": "Чекаємо поле логіна...",
        "log_tm_login_found": "Поле логіна знайдено",
        "log_tm_login_not_found": "Поле логіна не знайдено... ({attempt}/180)",
        "log_tm_window_not_found": "Вікно не знайдено... ({attempt}/180)",
        "log_tm_search_err": "Помилка пошуку: {e}",
        "log_tm_timeout": "Таймаут поля логіна (3 хв)",
        "log_tm_performing_login": "Виконуємо вхід...",
        "log_tm_err_login_field": "Поле логіна не знайдено!",
        "log_tm_login_entered": "Логін введено",
        "log_tm_err_pass_field": "Поле пароля не знайдено!",
        "log_tm_pass_entered": "Пароль введено",
        "log_tm_err_btn": "Кнопка Вхід не знайдена!",
        "log_tm_btn_clicked": "Натиснуто Вхід",
        "log_tm_login_err": "Помилка входу: {e}",
        "log_tm_update_cycle": "Цикл оновлення {current}/{max}",
        "log_tm_login_ok": "Вхід успішний",
        "log_tm_update_fail": "Вхід не вдався після оновлень",

        "log_tm_start": "Запуск Telemart...",
        "log_tm_login": "Вхід в акаунт...",
        "log_tm_success": "Вхід виконано!",
        "log_monitor_start": "Запуск монітора...",
    }
}


def set_language(lang_code):
    global CURRENT_LANG
    CURRENT_LANG = lang_code


def get_language():
    return CURRENT_LANG


def tr(key, **kwargs):
    text = TRANSLATIONS.get(CURRENT_LANG, TRANSLATIONS["ru"]).get(key, key)
    try:
        return text.format(**kwargs)
    except Exception:
        return text