# src/teleauto/gui/constants.py
import sys

# Размеры и геометрия
ROW_HEIGHT = 35
CORNER_RADIUS = 12

# Цвета
FRAME_BG = "#2C2C2E"
BORDER_COLOR = "#3A3A3C"

# macOS dark theme
CARD_BG = "#2C2C2E"
CARD_BORDER = "#3A3A3C"
CARD_HEIGHT = 72
CARD_RADIUS = 12
TEXT_PRIMARY = "#FFFFFF"
TEXT_SECONDARY = "#8E8E93"
ACCENT_BLUE = "#0A84FF"
SUCCESS_GREEN = "#32D74B"
WARNING_YELLOW = "#FFD60A"
ERROR_RED = "#FF453A"
BODY_FONT = "Segoe UI"
ICON_BG_GREEN = "#1C3829"
ICON_BG_BLUE = "#1A2938"
ICON_BG_TEAL = "#1A2E35"

# Шрифты
EMOJI_FONT_FAMILY = "Segoe UI Emoji" if sys.platform == "win32" else "Apple Color Emoji"
EMOJI_FONT = (EMOJI_FONT_FAMILY, 12)

MAIN_FONT_FAMILY = "Segoe UI"

VERSION = "v1.0"

# Intervals (seconds)
NETWORK_MONITOR_INTERVAL = 3
VPN_CHECK_INTERVAL = 5
VPN_RECONNECT_DELAY = 2
VPN_NO_PROFILES_DELAY = 3
VPN_NO_INTERNET_DELAY = 5
TELEMART_LAUNCH_DELAY = 5
TELEMART_KILL_DELAY = 1
TELEMART_WINDOW_TIMEOUT = 180
TELEMART_MAX_CYCLES = 5
NTP_TIMEOUT = 2
HTTP_SYNC_TIMEOUT = 3
SOCKET_CHECK_TIMEOUT = 3
UPDATER_API_TIMEOUT = 5
TOTP_REFRESH_INTERVAL = 1000  # ms
LED_BLINK_INTERVAL = 600      # ms
PING_TIMEOUT = 1000            # ms

# VPN Backoff
VPN_BACKOFF_BASE = 2
VPN_BACKOFF_MULTIPLIER = 1.5
VPN_BACKOFF_MAX = 60