# src/teleauto/gui/constants.py
import sys

# Размеры и геометрия
ROW_HEIGHT = 35
CORNER_RADIUS = 6

# Цвета
FRAME_BG = "#181818"
BORDER_COLOR = "#333333"

# Шрифты
EMOJI_FONT_FAMILY = "Segoe UI Emoji" if sys.platform == "win32" else "Apple Color Emoji"
EMOJI_FONT = (EMOJI_FONT_FAMILY, 12)

MAIN_FONT_FAMILY = "Unbounded"

VERSION = "v1.3"

# Intervals (seconds)
NETWORK_MONITOR_INTERVAL = 3
VPN_CHECK_INTERVAL = 5
VPN_RECONNECT_DELAY = 2
VPN_NO_PROFILES_DELAY = 3
VPN_NO_INTERNET_DELAY = 5
TELEMART_LAUNCH_DELAY = 5
TELEMART_KILL_DELAY = 1
TELEMART_WINDOW_TIMEOUT = 180
TELEMART_MAX_CYCLES = 5
NTP_TIMEOUT = 2
HTTP_SYNC_TIMEOUT = 3
SOCKET_CHECK_TIMEOUT = 3
UPDATER_API_TIMEOUT = 5
TOTP_REFRESH_INTERVAL = 1000  # ms
LED_BLINK_INTERVAL = 600      # ms
PING_TIMEOUT = 1000            # ms

# VPN Backoff
VPN_BACKOFF_BASE = 2
VPN_BACKOFF_MULTIPLIER = 1.5
VPN_BACKOFF_MAX = 60